version: 2.1

orbs:
  release-management: salesforce/npm-release-management@dev:alpha

workflows:
  version: 2
  test-and-release:
    jobs:
      - release-management/validate-pr:
          filters:
            branches:
              ignore: main
      - release-management/release-package:
          tag: beta
          sign: true
          prerelease: true
          filters:
            branches:
              only: ctc-testing-2
