version: 2.1
#####
orbs:
  release-management: salesforce/npm-release-management@dev:alpha

workflows:
  version: 2
  test-and-release:
    jobs:
      - release-management/validate-pr:
          filters:
            branches:
              ignore: main
      - release-management/test-package:
          name: node-latest
          node_version: latest
      - release-management/release-package:
          sign: true
          github-release: true
          requires:
            - node-latest
          filters:
            branches:
              only: main
      - release-management/release-package:
          requires:
            - node-latest
          tag: beta
          sign: true
          prerelease: true
          filters:
            branches:
              only: ctc-testing-2
  test-ts-update:
    triggers:
      - schedule:
          cron: 0 0 * * *
          filters:
            branches:
              only:
                - main
    jobs:
      - release-management/test-ts-update
